function r = BZspline(p0,p1,p2,p3,t)
% BZSPLINE(p0,p1,p2,p3,t) returns the Bezier spline functions R given the 
%   4 unit quaternions P0, P1, P2, P3 and the time instant T


	r = Lerp(...
            Lerp( ...
                Lerp(p0,p1,t), ...
                Lerp(p1,p2,t),...
                t...
                ),...
            Lerp( ...
                Lerp(p1,p2,t), ...
                Lerp(p2,p3,t), ...
                t ...
                ), ...
            t ...
            );
end