function r = BZspline(p0,p1,p2,p3,t)
	r = Lerp(...
            Lerp( ...
                Lerp(p0,p1,t), ...
                Lerp(p1,p2,t),...
                t...
                ),...
            Lerp( ...
                Lerp(p1,p2,t), ...
                Lerp(p2,p3,t), ...
                t ...
                ), ...
            t ...
            );
end