function r = CRspline(p0,p1,p2,p3,t)
	r = Lerp( ...
            Lerp( ...
                Lerp(p0,p1,t+1), ...
                Lerp(p1,p2,t), ...
                (t+1)/2 ...
                ), ...
            Lerp(...
                Lerp(p1,p2,t), ...
                Lerp(p2,p3,t-1), ...
                t/2 ...
                ), ...
            t ...
            );
end