function r = SBZspline(p0,p1,p2,p3,t)
% SBZSPLINE(p0, p1, p2, p3, t) returns the SBZ spline functions R given the
%   4 unit quaternions P0, P1, P2, P3 and the time T.

    r = Slerp( ...
              Slerp( ...
                    Slerp(p0,p1,t), ...
                    Slerp(p1,p2,t), ...
                    t ...
                    ), ...
              Slerp( ...
                    Slerp(p1,p2,t), ...
                    Slerp(p2,p3,t), ...
                    t ...
                    ), ...
              t ...
              );
end