function r = SBZspline(p0,p1,p2,p3,t)
    r = Slerp( ...
              Slerp( ...
                    Slerp(p0,p1,t), ...
                    Slerp(p1,p2,t), ...
                    t ...
                    ), ...
              Slerp( ...
                    Slerp(p1,p2,t), ...
                    Slerp(p2,p3,t), ...
                    t ...
                    ), ...
              t ...
              );
end