function r = SCRspline(p0,p1,p2,p3,t)
    r = Slerp( ...
              Slerp( ...
                    Slerp(p0,p1,t+1), ...
                    Slerp(p1,p2,t), ...
                    (t+1)/2 ...
                    ), ...
              Slerp( ...
                    Slerp(p1,p2,t), ...
                    Slerp(p2,p3,t-1), ...
                    t/2 ...
                    ),...
              t ...
              );
end