function r = SUBspline(p0,p1,p2,p3,t)
    r = Slerp( ...
              Slerp( ...
                    Slerp(p0,p1,(t+2)/3), ...
                    Slerp(p1,p2,(t+1)/3), ...
                    (t+1)/2 ...
                    ), ...
              Slerp( ...
                    Slerp(p1,p2,(t+1)/3), ...
                    Slerp(p2,p3,t/3), ...
                    t/2 ...
                    ), ...
              t ...
              );
end