function r = SUBspline(p0, p1, p2, p3, t)
% SUBSPLICE(p0, p1, p2, p3, t) returns the SUB spline functions R given the
%   4 unit quaternions P0, P1, P2, P3 and the time T.

    r = Slerp( ...
              Slerp( ...
                    Slerp(p0,p1,(t+2)/3), ...
                    Slerp(p1,p2,(t+1)/3), ...
                    (t+1)/2 ...
                    ), ...
              Slerp( ...
                    Slerp(p1,p2,(t+1)/3), ...
                    Slerp(p2,p3,t/3), ...
                    t/2 ...
                    ), ...
              t ...
              );
end