function r = UBspline(p0,p1,p2,p3,t)
    r = Lerp( ...
            Lerp( ...
                Lerp(p0,p1,(t+2)/3), ...
                Lerp(p1,p2,(t+1)/3), ...
                (t+1)/2 ...
                ), ...
            Lerp( ...
                Lerp(p1,p2,(t+1)/3), ...
                Lerp(p2,p3,t/3), ...
                t/2.), ...
            t ...
            );
end