function r = CRspline(p0,p1,p2,p3,t)
% CRSPLINE(p0,p1,p2,p3,t) returns the spline functions R given the 4 unit 
%   quaternions P0, P1, P2, P3 and the time instant T

	r = Lerp( ...
            Lerp( ...
                Lerp(p0,p1,t+1), ...
                Lerp(p1,p2,t), ...
                (t+1)/2 ...
                ), ...
            Lerp(...
                Lerp(p1,p2,t), ...
                Lerp(p2,p3,t-1), ...
                t/2 ...
                ), ...
            t ...
            );
end