function r = SCRspline(p0,p1,p2,p3,t)
% SCRSPLINE(p0, p1, p2, p3, t) returns the SCR spline functions R given the
%   4 unit quaternions P0, P1, P2, P3 and the time T.

    r = Slerp( ...
              Slerp( ...
                    Slerp(p0,p1,t+1), ...
                    Slerp(p1,p2,t), ...
                    (t+1)/2 ...
                    ), ...
              Slerp( ...
                    Slerp(p1,p2,t), ...
                    Slerp(p2,p3,t-1), ...
                    t/2 ...
                    ),...
              t ...
              );
end