function r = UBspline(p0, p1, p2, p3, t)
% UBSPLINE(p0, p1, p2, p3, t) returns the UB spline functions R given the 4
%   unit quaternions P0, P1, P2, P3 and the time T.

    r = Lerp( ...
            Lerp( ...
                Lerp(p0,p1,(t+2)/3), ...
                Lerp(p1,p2,(t+1)/3), ...
                (t+1)/2 ...
                ), ...
            Lerp( ...
                Lerp(p1,p2,(t+1)/3), ...
                Lerp(p2,p3,t/3), ...
                t/2.), ...
            t ...
            );
end